# Please make sure that the `needs` field for the `conclusion` job
# are updated when adding new jobs!

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -D elided_lifetimes_in_paths -D explicit_outlives_requirements -D unsafe_op_in_unsafe_fn -D unused_extern_crates -D unused_lifetimes -D unreachable_pub"
  RUSTUP_MAX_RETRIES: 10

jobs:
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}
    env:
      CC: deny_c
      RUST_CHANNEL: stable
      USE_SYSROOT_ABI: ''

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup default ${{ env.RUST_CHANNEL }}
          rustup component add --toolchain ${{ env.RUST_CHANNEL }} rust-src
          # We always use a nightly rustfmt, regardless of channel, because we need
          # --file-lines.
          rustup toolchain add nightly --profile minimal
          rustup component add --toolchain nightly rustfmt
