# Please make sure that the `needs` field for the `conclusion` job
# are updated when adding new jobs!

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Rust
        env:
          CI: 1
        run: |
          rustup component add --toolchain stable rust-src
          rustup toolchain add nightly --profile minimal
          rustup component add --toolchain nightly rustfmt
