# Please make sure that the `needs` field for the `conclusion` job
# are updated when adding new jobs!

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}
    env:
      CI: 1
      RUST_CHANNEL: stable

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup default ${{ env.RUST_CHANNEL }}
          rustup component add --toolchain ${{ env.RUST_CHANNEL }} rust-src
          # We always use a nightly rustfmt, regardless of channel, because we need
          # --file-lines.
          rustup toolchain add nightly --profile minimal
          rustup component add --toolchain nightly rustfmt
