name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -D elided_lifetimes_in_paths -D explicit_outlives_requirements -D unsafe_op_in_unsafe_fn -D unused_extern_crates -D unused_lifetimes -D unreachable_pub"
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Rust toolchain
        shell: pwsh
        run: |
            rustup update --no-self-update nightly
            rustup default nightly
            rustup component add --toolchain nightly rust-src
            # We always use a nightly rustfmt, regardless of channel, because we need
            # --file-lines.
            rustup toolchain add nightly --profile minimal
            rustup component add --toolchain nightly rustfmt
