on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}
     env:
      CI: true

    strategy:
      matrix:
        os: [windows-latest, windows-latest, windows-latest, windows-latest, windows-latest]

    steps:
      - name: Install Rust toolchain
        run: |
          rustup toolchain add nightly --profile minimal
          rustup component add --toolchain nightly rustfmt
